const users = [{
  "id": 1,
  "first_name": "Jacquetta",
  "last_name": "Ingliby",
  "username": "user1",
  "password": "pass_user1",
  "email": "jingliby0@sina.com.cn"
}, {
  "id": 2,
  "first_name": "Honor",
  "last_name": "Summerly",
  "username": "user2",
  "password": "pass_user2",
  "email": "hsummerly1@microsoft.com"
}, {
  "id": 3,
  "first_name": "Sumner",
  "last_name": "Maymond",
  "username": "user3",
  "password": "pass_user3",
  "email": "smaymond2@usda.gov"
}, {
  "id": 4,
  "first_name": "Morna",
  "last_name": "Tithacott",
  "username": "user4",
  "password": "pass_user4",
  "email": "mtithacott3@networksolutions.com"
}, {
  "id": 5,
  "first_name": "Suzie",
  "last_name": "Hainning",
  "username": "user5",
  "password": "pass_user5",
  "email": "shainning4@rediff.com"
}, {
  "id": 6,
  "first_name": "Lisabeth",
  "last_name": "Piccop",
  "username": "user6",
  "password": "pass_user6",
  "email": "lpiccop5@wix.com"
}, {
  "id": 7,
  "first_name": "Verney",
  "last_name": "Littrick",
  "username": "user7",
  "password": "pass_user7",
  "email": "vlittrick6@360.cn"
}, {
  "id": 8,
  "first_name": "Lydon",
  "last_name": "Whyke",
  "username": "user8",
  "password": "pass_user8",
  "email": "lwhyke7@discovery.com"
}, {
  "id": 9,
  "first_name": "Adolph",
  "last_name": "Bratton",
  "username": "user9",
  "password": "pass_user9",
  "email": "abratton8@dion.ne.jp"
}, {
  "id": 10,
  "first_name": "Mariele",
  "last_name": "Dumbrall",
  "username": "user10",
  "password": "pass_user10",
  "email": "mdumbrall9@examiner.com"
}];

export default users;
